---
title: "Untitled"
author: "Alberto Filosa"
date: "30/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Lecture 1: 02/10/2020 -->
# Scenario
Huge amount of data on social media through various devices. Information processig fully integraated within object and activities.

information provided in real time on various social platform:

* entities, books
* events, launch of a new product
* news, entertainment, politics
* relationships between etities

when we collect data, we need to transform information, oragnized in classified data, in to knowledge, so awareness and understanding in which info can be useful.

transorm data in relevant, valid, new and potentially useful information on social media, which can be transformed into knowledge used by different actors and purpose.

sma used for:

* Life quality (transaction)
* Brand reputation (awarness of the brand, sentiment, bad comments, consolid reputation, ect.)
* Forecasting the performance of finance markets.

not a simple process, too much info -> no info


## Internet
global system to connect computers around the world. TCP/IP protocols allow devices connected, interoperability between different system.

world wide web -> communication system, browse resources .

uri -> uniquely identifies a generic resource (ex: web address, url, document, image, ect.)

Data:
* structued (relational scheme)
* semi structured (no tabular scheme, but tags)
* unstrucured (no scheme)

html files -> readabe by machine

<!-- Lecture 2: 02/10/2020 -->
## Social Media
The social aspect of communication was to facilitate interaction between people who shared strong relationships, the same interests or find themselves working together in specific geographical contexts. The aviability of information is made possibl also by the presence and diffusion of Web Browser, Search Engines and *Social Media*.

There are three main distinction between data collected trhough the Web:

* *Virtual Data* (or Provoked Data), obatined through conventional research methods, such as queries online, and these answers are provided by users following specific questions;
* *Digitized Data*, analog data transformed in another digital formats (e-books, music, etc.);
* *Digital Data*, traces left by users, such as page visits or interactions with social media. In this case they are generated spontaneously by the users visiting a web page.

Social Media has specific characteristics:
* Interactive web 2.0 applications;
* Contents are generated by the users (posts, comments, etc.);
* Users create service-specific profiles;
* Social Media facilitates the development of online social networks.

The *Theory of Social Presencce* states that media differ in degree of social presence between the influence of the degree of intimacy and immediacy of the means of communication.

> The higher the social presence, the larger the social influence that the communication partners have on each other’s behavior

The *Media Richness Theory* is based on the assumption that the goal of any communication is the resolution of ambiguity and the reduction of uncertainty. The media differs in the degree of information richness they have. The concept of *Self Presentation* states that in any type of social interaction people have a desire to control the impressions of other people. This concept is related to self-disclososure

> Social media are **interactive computer-mediated** technologies that facilitate the **creation and sharing of information**, ideas, career interests and other forms of expression via **virtual communities** and networks.

A ***U***ser-***G***enerated ***C***ontent (**UGC**) is any form of content created by users of online system made avaiable on social media. The reason for creating UGC are:

* Implicit Incentives, not based on anything tangible, not directly monetizable. Social Incentives are the most common form; a user feels as active user of the community, also through the interaction of friends. It also improve the customer experience when purchasing a product;
* Explicit Incentives, referred to tangible rewards. They are easily understood by most people and have immediate value regardless of the size of the community (contest, voucher, etc.). The main disadvantage is they can make user believe that the only reason of partecipating is explicit incentive, reducing the influence of other type of interactions.

A Virtual Community is made up of social network of individuals who interact through means of communication, crossing any kind of boundaries in order to pursue mutual interests.

A Social Network is a social structure made up of a set of individuals, a series of dyadic links and other social interactions of social actors. There are many methods to analyze the structure of social entities, called ***S***ocial ***N***etwork ***A***nalysis (**SNA**), to identify local and global patterns and examine network dynamics.

<!-- The evolution of Social Media -->

There are many type of social media:

* *Blog*, a website containing one or more chronological posts that interactively discuss a certain topic;
* *Microblog*, publicational textual or multimedial content on the net;
* *News Sites*, the paper edition of the main newspaper. In these sites is possible to interact with other people;
* *Forums*, discussion sections in an IT platform or single sections;
* *Social Networking Sites*;
* *Virtual Game Worlds*;
* *Virtual Social Worlds*;
* *Content Communities*.

These sites produce differente type of data:

* *Articles*, mainly form news sites;
* *Posts*, generally blog and Social Networking Sites;
* *Tweets*, Twitter's content
* *Threads*, a conversation developed between multiple users;
* *Reviews*, ratings left by users;
* *Images* and *Videos*.