---
title: "Text Mining and Search"
author: "Alberto Filosa"
date: "29/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Lecture 1: 29/09/2020 -->
# Introduction

> Text mining is a burgeoning new field that attempts to glean meaningful information from natural language text. It may be loosely characterized as the process of analyzing text to extract information that is useful for particular purposes.

*Text mining* is generally used to denote any system that analyzes large quantities of text and detects lexical or linguistic patterns excracting useful information.

It is generally used for sentiment analysis, document summarization, news and other reccomendation and text analytics.

Data mining can be more characterized as the extraction of implicit, unknown, and potentially useful information from data. With text mining, the information extracted is clearly and explicit in the text.

There are several problems about Text Mining: first, document in an unsctrutured form are not accesible to be used by computers, many data are not well organized and natural language text contains ambiguites on a lexical, syntactical and semantic levels.

The Information Retrieval make it easier to find things on the Web because it finds useful answers in a collection.

The main tasks affected by Text Mining are:

* *Text Summarization*, that produce a condensed representation of the input text;
* *Information Retrieval*, that  identifies the most relevant documents to the query (used in Web Search Engine);
* *Content Based Recommender System*, that define the user profile and suggests the affinity of the research;
* *Text Classification*, that define categories according to their content (e.i. Sentiment Analysis);
* *Document Clustering*, an unsupervised learning in which there is no predefined classes, but only groups of document that share the similar topics.

<!-- Lecture 2: 01/10/2020 -->
## Basic Text Processing
*Basic Text Processing* is often the first step in any text mining application. It consists of several layers of simple processing such as tokenization, lemmatization or normalization. The purpose of analyzing texts can be either predictive or exploratory.

*Predictive Analysis* develope computer programs that automatically detect a particular concept within a span of text. Main examples are:

* Opinion Mining (positive or negative sentences)
* Sentiment Analysis, like the world; 
* Bias detection;
* Information Extraction automatically detect that a short seuence of words belongs to a particulary entity type;
* Relation Learning automatically detect pairs of entities that share a particular relation;
* Text Driven Forecasting monitors incoming text and making prediction about external events or trends;
* Temporal Summarization monitor incoming text about a news event and predicting whether a sentence should be included in an on-going summary of the event.

*Exploratory Analyis*, develop computer programs that automatically discover interesting and useful patterns in text collections.

Metadata associated with a document is data related to the document. In consist of descriptive, related to the creation of the document and semantinc metadata